server:
  port: 8765

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  output:
    ansi:
      enabled: always
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
#        - id: example
#          uri: lb://example
#          predicates:
#            - Path=/example/**
#          filters:
#            - RewritePath=/example/(?<path>.*), /$\{path}
#        - id: example
#          uri: lb://example
#          predicates:
#            - Path=/home
#          filters:
#            - RewritePath=/example/home/home, /$\{path}
#        - id: deal
#          uri: lb://deal
#          predicates:
#            - Path=/deal/**
#          filters:
#            - RewritePath=/deal/(?<path>.*), /$\{path}
#        - id: deal
#          uri: lb://deal
#          predicates:
#            - Path=/deal/admin/application
#          filters:
#            - RewritePath=/deal/v2/deal/admin/application/2, /