server:
  port: 8765

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  output:
    ansi:
      enabled: always
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
#        - id: deal
#          uri: lb://deal
#          predicates:
#            - Path=/deal/**
#          filters:
#            - RewritePath=/deal/(?<path>.*), /$\{path}
        - id: deal
          uri: lb://deal
          predicates:
            - Path=/deal/admin/application/*
          filters:
            - RewritePath=/deal/admin/application/(?<segment>.*), /v2/deal/admin/application/${segment}
        - id: deal-1
          uri: lb://deal
          predicates:
            - Path=/deal/admin/application
          filters:
            - RewritePath=/deal/admin/application, /v2/deal/admin/application
