server:
  port: 8765

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  output:
    ansi:
      enabled: always
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: example
          uri: lb://example
          predicates:
            - Path=/example/**
          filters:
            - RewritePath=/example/(?<path>.*), /$\{path}