server:
  port: 8765

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  output:
    ansi:
      enabled: always
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: deal-application-by-id
          uri: lb://deal
          predicates:
            - Path=/deal/admin/application/*
          filters:
            - RewritePath=/deal/admin/application/(?<segment>.*), /v2/deal/admin/application/${segment}
        - id: deal-application
          uri: lb://deal
          predicates:
            - Path=/deal/admin/application
          filters:
            - RewritePath=/deal/admin/application, /v2/deal/admin/application
        - id: deal
          uri: lb://deal
          predicates:
            - Path=/deal/**
          filters:
            - RewritePath=/deal/(?<path>.*), /$\{path}
        - id: openapi
          uri: http://localhost:${server.port}
          predicates:
            - Path=/v3/api-docs/**
          filters:
            - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs

springdoc:
  swagger-ui:
    urls:
      - name: deal
        url: /v3/api-docs/deal