name-template: 'v$NEXT_PATCH_VERSION'
tag-template: 'v$NEXT_PATCH_VERSION'
categories:
  - title: 'New features'
    labels:
      - 'type:features'

  - title: 'Bugs fixes'
    labels:
      - 'type:fix'

  - title: 'Documentation'
    labels:
      - 'type:documentation'

  - title: 'Configuration'
    labels:
      - 'type:config'

change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
template: |
  $CHANGES