version: '3.9'

name: dossier
services:
  zookeeper-dossier:
    image: confluentinc/cp-zookeeper:7.3.2
    container_name: zookeeper-dossier
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - kafka-dossier

  broker-dossier:
    image: confluentinc/cp-kafka:7.3.2
    container_name: broker-dossier
    ports:
      - 9092:9092
    depends_on:
      - zookeeper-dossier
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-dossier:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker-dossier:29092,PLAINTEXT_INTERNAL://localhost:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    networks:
      - kafka-dossier

networks:
  kafka-dossier:
    name: kafka-dossier
    driver: bridge

