openapi: 3.0.3
info:
  title: Swagger Deal - OpenAPI 3.0
  version: 1.0.11
servers:
  - url: https://localhost:8081/v1
tags:
  - name: deal
paths:
  /v1/application:
    post:
      tags:
        - application
      summary: Prescoring + request to calculate possible credit conditions
      operationId: postApplication
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoanApplicationRequestDTO'
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                format: List<LoanOfferDTO>
                items:
                  $ref: '#/components/schemas/LoanOfferDTO'
  /v1/application/offer:
    put:
      tags:
        - application
      summary: choose 1 offer
      operationId: putOffer
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoanOfferDTO'
      responses:
        '200':
          description: successful operation
components:
  schemas:
    LoanApplicationRequestDTO:
      required:
        - amount
        - term
        - firstName
        - lastName
        - birthdate
        - passportSeries
        - passportNumber
      type: object
      properties:
        amount:
          type: number
          format: BigDecimal
          example: 10000
          minimum: 10000
        term:
          type: integer
          example: 6
          minimum: 6
        firstName:
          type: string
          example: Ivan
        lastName:
          type: string
          example: Ivanov
        middleName:
          type: string
          example: Ivanovich
        email:
          type: string
          example: qwerty@gmail.com
          pattern: '[\w\.]{2,50}@[\w\.]{2,20}'
        birthdate:
          type: string
          format: date
          example: 2000-01-01
        passportSeries:
          type: string
          example: 1234
          minimum: 4
          maximum: 4
        passportNumber:
          type: string
          example: 123456
          minimum: 6
          maximum: 6
    LoanOfferDTO:
      required:
        - applicationId
        - requestedAmount
        - totalAmount
        - term
        - monthlyPayment
        - rate
        - isInsuranceEnabled
        - isSalaryClient
      type: object
      format: LoanOfferDTO
      properties:
        applicationId:
          type: integer
          format: int64
        requestedAmount:
          type: number
          format: BigDecimal
          minimum: 10000
        totalAmount:
          type: number
          format: BigDecimal
          minimum: 10000
        term:
          type: integer
          minimum: 6
        monthlyPayment:
          type: number
          format: BigDecimal
        rate:
          type: number
          format: BigDecimal
        isInsuranceEnabled:
          type: boolean
        isSalaryClient:
          type: boolean