#server:
#  port: 8765
#
spring:
  application:
    name: gateway
#  cloud:
#    gateway:
#      discovery:
#        locator:
#          enabled: true
#          lower-case-service-id: true
#      routes[0]:
#        id: example
#        uri: lb://example
#        predicates[0]: Path=/home/home
#        predicates[1]: Method=GET
#
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka
  config:
    import: "optional:configserver:http://localhost:8888"