server:
  port: 8080

spring:
  profiles:
    active: native
#  application:
#    name: proxy
#  cloud:
#    gateway:
#      routes:
#        - id: application-route
#          uri: ${APPLICATION_ROUTE_URI:http://localhost:8080}
#          predicates:
#            - Path=/home/**
#          filters:
#            - PrefixPath=/home
#            - AddResponseHeader=X-Powered-By,DanSON Gateway Service
