name: Credit-conveyor

on:
  pull_request:
    branches: ['develop']
  push:
    branches:
      - 'develop'
      - 'main'

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: '17'
      - name: maven package
        run: mvn -B clean package -DskipTests