openapi: 3.0.3
info:
  title: Swagger Deal - OpenAPI 3.0
  version: 1.0.11
servers:
  - url: https://localhost:8081/v1
tags:
  - name: deal
paths:
  /v1/deal/application:
    post:
      tags:
        - deal
      summary: calculate possible credit conditions.
      operationId: postCalculationApplication
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoanApplicationRequestDTO'
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                format: List<LoanOfferDTO>
                items:
                  $ref: '#/components/schemas/LoanOfferDTO'
  /v1/deal/offer:
    put:
      tags:
        - deal
      summary: choose 1 offer
      operationId: putOffer
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoanOfferDTO'
      responses:
        '200':
          description: successful operation
  /v1/deal/calculate/{applicationId}:
    put:
      tags:
        - deal
      summary: finish registration and calculate total credit amount
      operationId: putApplicationById
      parameters:
        - name: applicationId
          in: path
          required: true
          schema:
            type: integer
            format: long
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FinishRegistrationRequestDTO'
      responses:
        '200':
          description: successful operation
components:
  schemas:
    LoanApplicationRequestDTO:
      type: object
      properties:
        amount:
          type: number
          format: BigDecimal
          example: 10000
        term:
          type: integer
          example: 6
        firstName:
          type: string
          example: Ivan
        lastName:
          type: string
          example: Ivanov
        email:
          type: string
          example: qwerty@gmail.com
        birthdate:
          type: string
          format: date
          example: 2000-01-01
        passportSeries:
          type: string
          example: 1234
        passportNumber:
          type: string
          example: 123456
    LoanOfferDTO:
      type: object
      format: LoanOfferDTO
      properties:
        applicationId:
          type: integer
          format: int64
        requestedAmount:
          type: number
          format: BigDecimal
        totalAmount:
          type: number
          format: BigDecimal
        term:
          type: integer
        monthlyPayment:
          type: number
          format: BigDecimal
        rate:
          type: number
          format: BigDecimal
        isInsuranceEnabled:
          type: boolean
        isSalaryClient:
          type: boolean
    FinishRegistrationRequestDTO:
      type: object
      format: FinishRegistrationRequestDTO
      properties:
        gender:
          $ref: '#/components/schemas/Gender'
        maritalStatus:
          $ref: '#/components/schemas/MartialStatus'
        dependentAmount:
          type: integer
        passportIssueDate:
          type: string
          format: date
        passportIssueBranch:
          type: string
        employment:
          $ref: '#/components/schemas/EmploymentDTO'
        account:
          type: string
    EmploymentDTO:
      type: object
      format: EmploymentDTO
      properties:
        employmentStatus:
          $ref: '#/components/schemas/EmploymentStatus'
        employerINN:
          type: string
        salary:
          type: number
          format: BigDecimal
        position:
          $ref: '#/components/schemas/EmploymentPosition'
        workExperienceTotal:
          type: integer
        workExperienceCurrent:
          type: integer
    Gender:
      type: string
      enum:
        - MALE
        - FEMALE
        - NON_BINARY
    MartialStatus:
      type: string
      enum:
        - MARRIED
        - DIVORCED
        - SINGLE
        - WIDOW_WIDOWER
    EmploymentStatus:
      type: string
      enum:
        - UNEMPLOYED
        - EMPLOYED
        - SELF_EMPLOYED
        - BUSINESS_OWNER
    EmploymentPosition:
      type: string
      enum:
        - WORKER
        - MID_MANAGER
        - TOP_MANAGER
        - OWNER
