databaseChangeLog:
  - changeSet:
      id: 4
      author: vivannikov
      changes:
        - sqlFile:
            dbms: postgresql
            encoding: utf-8
            endDelimiter: \nGo
            relativeToChangelogFile: true
            splitStatements: true
            path: 20-create-application-table.sql
      rollback:
        - sqlFile:
            dbms: postgresql
            encoding: utf-8
            endDelimiter: \nGo
            relativeToChangelogFile: true
            splitStatements: true
            path: 20-drop-application-table.sql
  - changeSet:
      id: 7
      author: vivannikov
      changes:
        - sqlFile:
            dbms: postgresql
            encoding: utf-8
            endDelimiter: \nGo
            relativeToChangelogFile: true
            splitStatements: true
            path: 20-alter-application-table.sql