server:
  port: 8888

spring:
  profiles:
    active: native

---

server:
  port: 8888

spring:
  cloud:
    config:
      server:
        bootstrap: false
  #  cloud:
#    config:
#      server:
#        git:
#          uri: https://github.com/IvannikovVasiliy/insurance-config-server
#        default-label: main
  profiles:
    active: docker
