name: Credit-conveyor

on:
  pull_request:
    branches: ['develop']
  push:
    branches:
      - 'develop'
      - 'main'

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: maven package
        run: mvn -B clean package -DskipTests