spring:
  profiles:
    active: local
  application:
    name: discovery
  config:
    import: "optional:configserver:http://localhost:8888"

---

spring:
  profiles:
    active: docker
  application:
    name: discovery
  config:
    import: "optional:configserver:http://configuration:8888"
