server:
  port: 8083

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/dossier
    username: postgres
    password: postgres
  jpa:
    hibernate.ddl-auto: validate
    show-sql: true
  liquibase:
    change-log: classpath:db/changelog/changelog-master.yaml

kafka:
  group-id: dossier-ms-group
  topics:
    create-documents-topic: create-documents

dealService:
  hostPort: http://localhost:8081

mail:
  host: smtp.gmail.com
  port: 587
  email: ivannikovvasiliya@gmail.com

sftp:
  host: 172.18.9.135
  port: 22
  locationFiles: /var/sftp/Files
  sshHostsFileName: hosts.dat

logging:
  level:
    com.neoflex.creditconveyer.dossier: DEBUG