name: Credit-conveyor

on:
  pull_request:
    branches: ['*']
  push:
    branches:
      - 'develop'
      - 'main'

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - run: mv -f application/* .
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: maven package
        run: mvn -B clean package
      - name: Code-coverage
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
